# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- azure-pipelines

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:

- stage: build
  jobs:
    - job: build
      steps:
      - task: UseDotNet@2
        displayName: 'Use .NET 6'
        inputs:
          version: 6.x

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

      - task: PowerShell@2
        #displayName: "Set Hidi's version-number"
        name: setCurrProjVersion
        inputs:
          targetType: 'inline'
          script: |
            $xml = [Xml] (Get-Content .\src\Microsoft.OpenApi.Hidi\Microsoft.OpenApi.Hidi.csproj)
            $version = $xml.Project.PropertyGroup.Version
            echo $version
            echo "##vso[task.setvariable variable=version; isOutput=true]$version"

      - task: MSBuild@1
        displayName: 'Pack OpenApi Hidi'
        inputs:
          solution: src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj
          configuration: Release
          msbuildArguments: '/t:pack /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)/Nugets /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          arguments: -c Release --runtime win-x64 -p:PublishSingleFile=true --self-contained true --output $(Build.ArtifactStagingDirectory)/Microsoft.OpenApi.Hidi-v$(version) -p:PublishTrimmed=true
          projects: 'src/Microsoft.OpenApi.Hidi/Microsoft.OpenApi.Hidi.csproj'
          publishWebProjects: False
          zipAfterPublish: false

      - task: PublishBuildArtifacts@1
        displayName: 'Package Hidi'
        inputs: 
          ArtifactName: Nugets  
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/Nugets'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: Hidi'
        inputs: 
          ArtifactName: Microsoft.OpenApi.Hidi-v$(version)  
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/Microsoft.OpenApi.Hidi-v$(version)'
     
- stage: deploy
  # condition: and(contains(variables['build.sourceBranch'], 'refs/heads/vnext'), succeeded())
  dependsOn: build
  jobs:
    - deployment: deploy
      dependsOn: []
      environment: none
      strategy:
        runOnce:
          deploy:
            pool:
              vmImage: ubuntu-latest
            steps:
            - task: DownloadPipelineArtifact@2
              displayName: Download hidi executable from artifacts
              inputs:
                source: current
            - task: PowerShell@2
              inputs:
                targetType: 'inline'
                script: |
                  $artifactMainDirectory = Get-ChildItem -Filter Microsoft.OpenApi.Hidi-* -Directory -Recurse | select -First 1
                  $artifactName = $artifactMainDirectory.Name -replace "Microsoft.OpenApi.Hidi-", ""
                  #Set Variable $artifactName
                  
                  Write-Host "##vso[task.setvariable variable=artifactMainDirectory; isSecret=false; isOutput=true;]$artifactMainDirectory.FullName"
                  Write-Host "##vso[task.setvariable variable=artifactName; isSecret=false; isOutput=true;]$artifactName"
              displayName: 'Fetch Artifact Name'
            - task: GitHubRelease@1
              displayName: 'GitHub release (edit)'
              inputs:
                gitHubConnection: 'Github-MaggieKimani1'
                repositoryName: MaggieKimani1/OpenAPI.NET
                action: edit
                tag: $(artifactName)
                title: 'Microsoft.OpenApi.Hidi-$(artifactName)'
                releaseNotesSource: inline
                assets: '$(artifactMainDirectory)\**\*.exe'
                assetUploadMode: replace
                changeLogType: issueBased